config/routes.rb
ShakeReport::Application.routes.draw do
  get "applications/index"

  root :to => 'applications#index'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'authentication', to: 'sessions#index', as: 'authentication'

  resources :invitations, only: [:index]

  resources :applications, only: [:index , :create] do
    resources :builds, only: [:index, :create]
    resources :reports, only: [:index, :show] do
      post :create_jira_issue
      put :update_status
      put :new_build, on: :collection
      resources :comments
    end

    resources :settings, only: [:index] do
      put :update_jira
      put :add_user, on: :collection
      put :invite, on: :collection
    end
  end

  resources :reports, only: [] do
    resources :comments, controller: "reports/comments"
  end


  resources :alert_mails, only: [:index, :create, :destroy]


  #################
  #     API       #
  #################
  namespace :api do
    resources :reports, only: [:create]
  end

end

app/models/setting.rb
class Setting
  include Mongoid::Document
  
  field :values, type: Hash

  embedded_in :application
  
  def set(key, value)
    values = {} if values.nil?
    values[key.to_s] = value
  end
  
  def get(key)
    values.nil? ? nil : values[key.to_s]
  end
  
  def jira_valid?
    client = Jira::Client.default_client
    project_key = get(:jira_project_key)
    issue_id = get(:jira_issue_id)
    return client && project_key && issue_id && client.connected?
  end
  
  private
  def self.create_settings
    Setting.create!(values: {})
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  before_filter :ensure_application
  before_filter :init_variables

  # GET /settings
  # GET /settings.json
  def index
    @invitations = current_application.invitations if current_user.is_admin?(current_application)
    @accesses = current_application.accesses if current_user.is_admin?(current_application)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @settings }
    end
  end

  def update_jira
    project_key = params[:project]
    puts params
    issue_id = params["issue_#{project_key}"]
    @settings.set(:jira_project_key, project_key)
    @settings.set(:jira_issue_id, issue_id)
    respond_to do |format|
      if @settings.save
        format.html { redirect_to application_settings_url(current_application), notice: 'Settings was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "index" }
        format.json { render json: @settings.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_user
    user = User.where(name: params[:application_access][:username]).exists? ? User.find_by(name: params[:application_access][:username]) : nil
    respond_to do |format|
      if !user.nil? && ApplicationAccess.create(application_id: current_application.id, user_id: user.id).errors.empty?
        format.html { redirect_to application_settings_url(current_application), notice: "User '#{user.name}' added to #{current_application.name}." }
        format.json { head :no_content }
      else
        format.html { redirect_to application_settings_url(current_application), alert: "An error occured while adding '#{params[:application_access][:username]}' to #{current_application.name}." }
        format.json { head :no_content, status: :unprocessable_entity }
      end
    end
  end

  def invite
    email = params[:invitation][:email]
    invitation = Invitation.new(email: email, application: current_application)
    respond_to do |format|
      if invitation.save
        format.html { redirect_to application_settings_url(current_application), notice: "Invitation sent to #{invitation.email}" }
        format.json { head :no_content }
      else
        format.html { redirect_to application_settings_url(current_application), alert: "An error occured while inviting #{invitation.email}" }
        format.json { head :no_content, status: :unprocessable_entity }
      end
    end
  end

  protected
  def init_variables
    @settings = current_application.setting
    get_jira_project
  end

  def get_jira_project
    @jira_project_key = @settings.get(:jira_project_key)
    @jira_issue_id = @settings.get(:jira_issue_id)
    @jira_projects = $jira_client.projects if Jira::Client.enabled? && $jira_client.connected?
  end
end

app/views/settings/_accesses.html.erb
<div id="accesses" class="row well">

  <h4>Users</h4>

  <div class="new_mail_form">
    <%= form_for(Invitation.new(application_id: current_application), method: :put, url: invite_application_settings_url(current_application), html: {class: "form-inline"}) do |f| %>
        <div class="form-group">
          <%= f.text_field :email, placeholder: "Email of the person you want to invite", size: 50 %>
        </div>

        <%= f.submit "Invite", class: "btn btn-primary"%>

    <% end %>
  </div>

  <table class="table table-bordered table-hover">
    <thead>
    <tr>
      <th>Pending Invitations</th>
    </tr>
    </thead>
    <tbody>
    <% @invitations.each do |invite| %>
        <tr>
          <td><%= invite.email %></td>
        </tr>
    <% end %>
    </tbody>
  </table>




  <table class="table table-bordered table-hover">
    <thead>
    <tr>
      <th>Authorized Users</th>
    </tr>
    </thead>
    <tbody>
    <% @accesses.each do |access| %>
        <tr>
          <td><%= access.user.name %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/settings/_jira.html.erb
<div id="jira" class="row well">
	<h4>Jira integration</h4>

	<% if Jira::Client.enabled? && Jira::Client.default_client.connected? %>
	<p>
		Host: <%= link_to Jira::Client.default_client.host, Jira::Client.default_client.host, target: "blank"%> <br/>
		User: <%= Jira::Client.default_client.user %>
	</p>
		<%= form_tag(application_setting_update_jira_url(current_application.id, @settings.id), method: "put", class: "form-horizontal", role: "form") do %>
			<div class="form-group">
			    <label class="col-sm-2 control-label">Project</label>
			    <div class="col-sm-3">
					<%= select_tag "project", options_for_select(@jira_projects.map{|p| [p.name, p.key]}, @jira_project_key), class: "form-control"%>
			    </div>
			 </div>

			<div class="form-group">
			    <label class="col-sm-2 control-label">Issue Type</label>
			    <div class="col-sm-3">
					<% @jira_projects.each do |project| %>

						<%= select_tag "issue_#{project.key}", options_for_select(project.issue_types.map{|i| [i.name, i.id]}, @jira_issue_id), class: "issue form-control" %>
					<% end %>
			    </div>
			 </div>
			<div class="form-group">
			    <div class="col-sm-offset-2 col-sm-10">
					<%= submit_tag("Save", class: 'btn btn-default', type: "submit") %>
			    </div>
			 </div>
		<% end %>
	<% end %>
</div>

<script>
// change the issue select to display the issues of the selected project
$(function() {
	var project_key = "<%= @jira_project_key %>"
	$('select.issue:not(#issue_'+project_key+')').hide();
	$('select.issue#issue_'+project_key).show();
});

$("select#project").change(function() {
    var project_key = $(this).val();
	$('select.issue:not(#issue_'+project_key+')').hide();
	$('select.issue#issue_'+project_key).show();
});
</script>

app/views/settings/index.html.erb
<h3>Settings</h3>

<%= render 'jira' %>

<%= render 'accesses' if current_user.is_admin?(current_application)%>