config/routes.rb
ShakeReport::Application.routes.draw do
  get "applications/index"

  root :to => 'applications#index'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'authentication', to: 'sessions#index', as: 'authentication'

  resources :invitations, only: [:index]

  resources :applications, only: [:index , :create] do
    resources :builds, only: [:index, :create]
    resources :reports, only: [:index, :show] do
      post :create_jira_issue
      put :update_status
      put :new_build, on: :collection
      resources :comments
    end

    resources :settings, only: [:index] do
      put :update_jira
      put :add_user, on: :collection
      put :invite, on: :collection
    end
  end

  resources :reports, only: [] do
    resources :comments, controller: "reports/comments"
  end


  resources :alert_mails, only: [:index, :create, :destroy]


  #################
  #     API       #
  #################
  namespace :api do
    resources :reports, only: [:create]
  end

end

app/models/report.rb
class Report
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip
  include Mongoid::Commentable


  default_scope order_by(:updated_at => :desc)
  after_create :after_create_hook

  STATUS = {new: 0, available_on_next_build: 1 ,ready_to_test: 2, archived: 3}
  field :title, type: String
  field :message, type: String
  field :device_model, type: String
  field :os_version, type: String
  field :screenshot, type: String
  field :logs, type: String
  field :crash_logs, type: String
  field :dumped_view, type: String
  field :status, type: Integer, default: STATUS[:new]
  field :jira_ticket, type: String

  belongs_to :application
  belongs_to :build

  has_mongoid_attached_file :screen_capture
  
  validate :has_one_attribute_set
  
  scope :opened, where(:status => STATUS[:new])
  scope :available_on_next_build, where(:status => STATUS[:available_on_next_build])
  scope :ready_to_test, where(:status => STATUS[:ready_to_test])
  scope :archived, where(:status => STATUS[:archived])
  scope :today, where(:created_at.gte => Date.today)

  def message_for_ticket
    host = Rails.application.config.action_mailer.default_url_options[:host]
    m = "--------------------------------------------------------------\n"
    m = m + "OS: #{self.os_version}\n"
    m = m + "Device: #{self.device_model}\n"
    m = m + "--------------------------------------------------------------\n"
    m = m + message + "\n"
    m = m + "--------------------------------------------------------------\n"
    m = m + "Video: #{self.screen_capture.url}\n" if self.screen_capture_file_name
    m = m + "More info there: #{Rails.application.routes.url_helpers.application_report_url(self.application, self, host: host)}\n"
    m = m + "Created with Shake Report."
  end

  def after_create_hook
    emails = self.application.email_list
    ReportMailer.new_report_created(emails, self).deliver if !emails.empty?
  end

  protected
  def has_one_attribute_set
    if title.nil? && message.nil? && device_model.nil? && os_version.nil? && screenshot.nil? && logs.nil? && crash_logs.nil? && dumped_view.nil?
      errors.add(:title, 'or at least one attribute needs to be set')
    end
  end
end

app/controllers/api/reports_controller.rb
class Api::ReportsController < ApiController

  # POST api/reports
  # POST api/reports.json
  def create
    @report = current_application.reports.new(params[:report])
    if @report.save
      render json: @report, status: :created
    else
      render json: @report.errors, status: :unprocessable_entity
    end
  end

end

app/controllers/reports/comments_controller.rb
class Reports::CommentsController < ::CommentsController

  def create
    @comment = @model.create_comment!(params[:comment])
    if @comment.save
      flash[:notice] = 'Comment was successfully created.'
    else
      flash[:error] = 'Comment wasn\'t created.'
    end
    redirect_to :back
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  before_filter :ensure_application

  # GET /reports
  # GET /reports.json
  def index
    @status = params[:scope] ? params[:scope].to_sym : :new
    if @status == :archived
      @reports = current_application.reports.archived
    elsif @status == :available_on_next_build
      @reports = current_application.reports.available_on_next_build
    elsif @status == :ready_to_test
      @reports = current_application.reports.ready_to_test
    else
      @status = :new
      @reports = current_application.reports.opened
    end
    puts "status: #{@status}"
  
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = current_application.reports.find(params[:id])
    @show_jira = current_application.setting.jira_valid?
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # PUT /reports/1/update_status
  # PUT /reports/1/update_status.json
  def update_status
    @report = current_application.reports.find(params[:report_id])
    new_status = @report.status+1 < Report::STATUS.size ? @report.status+1 : @report.status
    
    respond_to do |format|
      if new_status != @report.status && @report.update_attributes(status: new_status)
        format.html { redirect_to application_report_url(@report.application, @report), notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        @show_jira = Setting.get_settings.jira_valid?
        format.html { render action: "show", notice: "The current status is the last level of report status available." }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/new_build
  # PUT /reports/new_build.json
  def new_build
    attributes = {status: Report::STATUS[:ready_to_test]}
    attributes[:fix_version] = params[:version] if params[:version]
    @reports = current_application.reports.available_on_next_build
    @count = @reports.count
    @reports.update_all(attributes) if @count > 0
    respond_to do |format|
      if @count > 0 && @reports
        format.html { redirect_to reports_url, notice: "New build created, #{@count} reports updated." }
        format.json { head :no_content }
      else
        format.html { redirect_to :back, alert: 'New build annouced, but not report was waiting for a new build.' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_jira_issue
    @report = current_application.reports.find(params[:report_id])
    settings = current_application.setting
    client = Jira::Client.default_client
    respond_to do |format|
      if client
        begin
          @jira_url = Jira::Client.default_client.create_issue_for_report(@report, settings.get(:jira_project_key), settings.get(:jira_issue_id))
          if @report.update_attributes({jira_ticket: @jira_url}) && @report.jira_ticket == @jira_url
            format.html { redirect_to application_report_url(current_application, @report), notice: "Jira issue successfully created: #{@jira_url}"}
            format.json { render json: @report, status: :created }
          else
            message = "An error occured during the linking of the report with the Jira ticket: #{@jira_url}"
            format.html { redirect_to application_report_url(current_application, @report), alert: message }
            format.json { render json: {error: message}, status: :unprocessable_entity }
          end
        rescue Jira::Error::NotConnectedError
          message = 'An error occured, Jira issue not created. Please check that you configuration is correct.'
          format.html { redirect_to application_report_url(current_application, @report), alert: message }
          format.json { render json: {error: message}, status: :unprocessable_entity }
        rescue Exception => e   
          message = "An error occured. #{e}"
          format.html { redirect_to application_report_url(current_application, @report), alert: message }
          format.json { render json: {error: message}, status: :unprocessable_entity }          
        end
      else  
        message = 'Jira not configured.'
        format.html { redirect_to application_report_url(current_application, @report), alert: message }
        format.json { render json: {error: message}, status: :method_not_allowed }
      end
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper

  def screenshot_tag(report)
  	raw "<img class=\"screenshot\" src=\"data:image/gif;base64,#{report.screenshot}\">"
  end
  
  def status_title(status_code)
    if Report::STATUS.keys.size > status_code
      "#{Report::STATUS.keys[status_code]}".gsub('_', ' ').capitalize
    else 
      nil
    end
  end
  
  def dumped_view_to_html(dumped_view)
    if dumped_view
      safe_string = h(dumped_view)
      space = "&nbsp;&nbsp;"
      to_html = safe_string.gsub(/\|/, space)
    end
    to_html || h(dumped_view)
  end
  
  def logs_to_html(logs)
    lines = h(logs).split("\n")
    to_html = ""
    lines.each_with_index do |line, index|
      odd = (index%2 == 0) ? "odd" : ""
      to_html += "<p class=\"log_line #{odd}\">#{line}</p>"
    end
    to_html || h(logs)
  end
end

app/views/reports/_form.html.erb
<%= simple_form_for @report, :html => {:multipart => true } do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :screenshot, as: :text %>
    <%= f.input :logs, as: :text  %>
    <%= f.input :crash_logs, as: :text  %>
    <%= f.input :dumped_view, as: :text  %>
	<%= f.file_field :screen_capture %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<div id="reports">
  <h1>Reports</h1>

  <ul class="nav nav-pills nav-justified reports-nav">
    <% Report::STATUS.each_key do |status| %>
        <li class="<%= "active" if @status == status %>">
            <%= link_to status.to_s.gsub('_', ' ').capitalize, application_reports_url(current_application, scope: status)  %>
        </li>
    <% end %>
  </ul>

  <table class="table table-bordered table-hover">
  	<thead>
    	<tr>
    	  <th>Title</th>
  		  <th>Created at</th>
		  <% if Report::STATUS[@status] > Report::STATUS[:available_on_next_build]%>
  		   <th>Fix version</th>
		  <% end %>
    	  <th></th>
   		</tr>
  	</thead>
  	<tbody>
  		<% @reports.each do |report| %>
  		  <tr>
  		    <td><%= report.title || "No title" %></td>
  			<td><%= report.created_at ? report.created_at.to_formatted_s(:short) : "N/A" %></td>
  		  <% if Report::STATUS[@status] > Report::STATUS[:available_on_next_build]%>
			<td><%= report.build.nil? ? "n/a" : link_to(report.build.title, report.build.itunes_url) %></td>
  		  <% end %>
  		    <td><%= link_to 'Show', application_report_path(current_application, report), class: "btn btn-primary" %></td>
  		  </tr>
  		<% end %>	
  	</tbody>
  </table>
</div>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/new_jira_issue.html.erb
create jira ticket

app/views/reports/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @report.title %></h3>
  </div>
  <div class="panel-body">
    <p>
      <strong>Status:</strong>
      <span class="label label-info">
      <% if status_title(@report.status + 1) %>
        <%= status_title(@report.status) %></span> Mark as
        <%= link_to status_title(@report.status + 1), application_report_update_status_path(current_application, @report), method: :put %> ?
      <% end %>
    </p>
    <p>
      <strong>Fix in build:</strong>
      <%= @report.build.nil? ? "n/a" : link_to(@report.build.title, @report.build.itunes_url)  %>
    </p>
    <p>
      <strong>Device:</strong>
      <%= @report.device_model || "n/a" %>
    </p>

    <p>
      <strong>OS:</strong>
      <%= @report.os_version || "n/a" %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @report.message %>
    </p>

  </div>
</div>


<ul id="myTab" class="nav nav-pills">
  <% if @report.screen_capture_file_name %>
    <li><a href="#video" data-toggle="tab">Video</a></li>
    <li><a href="#screenshot" data-toggle="tab">Screenshot</a></li>
  <% else %>
    <li><a href="#screenshot" data-toggle="tab">Screenshot</a></li>
  <% end %>
  <li><a href="#dumped-view" data-toggle="tab">Dumped View</a></li>
  <li><a href="#logs" data-toggle="tab">Logs</a></li>
  <% if @report.crash_logs %>
  <li><a href="#crash" data-toggle="tab">Crash</a></li>
  <% end %>
  <li><a href="#comments">Comments</a></li>

  <% if @report.jira_ticket %>
  <li class="pull-right"><%= link_to "Jira ticket", @report.jira_ticket, target: "blank" %></li>
  <% elsif @show_jira %>
  <li class="pull-right"><%= link_to "Create Jira ticket", application_report_create_jira_issue_url(current_application, @report), method: :post %></li>
  <% end %>
</ul>

<div id="myTabContent" class="tab-content">
  <% if @report.screen_capture_file_name %>
	 <div class="tab-pane fade in active" id="video">
     <p><a href="<%= @report.screen_capture.url %>">Download</a></p>
     <video width="320" height="480" controls>
       <source src="<%= @report.screen_capture.url %>" type="video/mp4">
     </video>
	 </div>
   <% end %>
   
	 <div class="tab-pane fade" id="screenshot">
	 	 <p><%= screenshot_tag(@report) %></p>
	 </div>
	 <div class="tab-pane fade" id="logs">
	 	<p><%= raw(logs_to_html(@report.logs)) %></p>
	 </div>
   <% if @report.crash_logs %>
	   <div class="tab-pane fade" id="crash">
	 	   <p><%= simple_format h(@report.crash_logs) %></p>
	   </div>
   <% end %>
	 <div class="tab-pane fade" id="dumped-view">
	 	<pre class=""><%= simple_format dumped_view_to_html(@report.dumped_view), {style: "width=300%"} %></pre>
	 </div>
</div>

<hr/>
 <div class="" id="comments">
  <% @report.comments_list.each do |comment| %>
  <div class="well comment level_<%= comment.level %>" style="margin-left: <%= comment.level * 20 %>px">
    <p class="author"> <%= comment.author %> <%= comment.level > 1 ? "replied:" : "commented:" %></p>
    <p class="content"> <%= comment.text %> </p>
    <!--<%= link_to "Reply", new_application_report_comment_path(current_application, :report_id => @report.id.to_s, :parent => comment.id.to_s), class: "reply" %>-->
  </div>
  <% end %>
  <div id="new_comment">
    <%= render :partial => '/comments/form', :locals => {:model => @report, :comment => Comment.new}%>
  </div>
</div> <!-- comments -->


<script>
  $(function () {
      $('#myTab a:first').tab('show');
  })
</script>