config/routes.rb
ShakeReport::Application.routes.draw do
  get "applications/index"

  root :to => 'applications#index'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'authentication', to: 'sessions#index', as: 'authentication'

  resources :invitations, only: [:index]

  resources :applications, only: [:index , :create] do
    resources :builds, only: [:index, :create]
    resources :reports, only: [:index, :show] do
      post :create_jira_issue
      put :update_status
      put :new_build, on: :collection
      resources :comments
    end

    resources :settings, only: [:index] do
      put :update_jira
      put :add_user, on: :collection
      put :invite, on: :collection
    end
  end

  resources :reports, only: [] do
    resources :comments, controller: "reports/comments"
  end


  resources :alert_mails, only: [:index, :create, :destroy]


  #################
  #     API       #
  #################
  namespace :api do
    resources :reports, only: [:create]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ShakeReport" %></title>
    <%= csrf_meta_tags %>


	<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">

    <%= stylesheet_link_tag "application", "font-awesome", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

  <% if current_user %>
      <header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
        <div class="container">
          <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a href="<%= root_url %>" class="navbar-brand">Shake Report</a>
          </div>
          <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
            <ul class="nav navbar-nav">
              <% if current_application %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Applications <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <% current_user.applications.each do |app| %>
                          <li><%= link_to app.name, application_reports_path(app)  %></li>
                      <% end %>
                    </ul>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reports <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <% Report::STATUS.each_key do |status| %>
                          <li>
                            <%= link_to status.to_s.gsub('_', ' ').capitalize, application_reports_url(current_application, scope: status)  %>
                          </li>
                      <% end %>
                    </ul>
                  </li>
                  <li><%= link_to "Builds", application_builds_url(current_application)  %></li>
                  <li><%= link_to "Settings", application_settings_url(current_application)  %></li>
              <% end %>
              <li>
                <% if current_user %>
                    <%= link_to "Sign out", signout_path %>
                <% else %>
                    <%= link_to "Sign in with Github", "/auth/github" %>
                <% end %>
              </li>
            </ul>
            <% if current_application %>
              <%= render "builds/new_build" %>
            <% end %>
          </nav>
        </div>
      </header>
  <% end %>


	<div class="bs-header" id="content">
    <div class="container">
      <% if flash[:notice] %>
          <div class="alert alert-success">
            <%= content_tag :div, flash[:notice], :id => "flash_notice" %>
          </div>
      <% end %>
      <% if flash[:alert] %>
          <div class="alert alert-danger">
            <%= content_tag :div, flash[:alert], :id => "flash_alert" %>
          </div>
      <% end %>

      <div class="row">
	    <div class="col-lg-12">
	      <%= yield %>
	    </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->
    </div> <!-- /container -->

  </body>
</html>